import com.smalko.scoreboard.controller.MatchScoreCalculationService;
import com.smalko.scoreboard.controller.MatchScoreModel;
import org.junit.jupiter.api.Test;

public class MatchScoreCalculationServiceTest {

    private final MatchScoreModel matchScoreModel = new MatchScoreModel();
    private final MatchScoreCalculationService matchScoreCalculationService = new MatchScoreCalculationService(matchScoreModel);

    @Test
    void plusPoint() {
        matchScoreCalculationService.addPoint(1);
        System.out.println(matchScoreModel.getPoint());
        matchScoreCalculationService.addPoint(1);
        System.out.println(matchScoreModel.getPoint());
        matchScoreCalculationService.addPoint(1);
        System.out.println(matchScoreModel.getPoint());
        matchScoreCalculationService.addPoint(0);
        System.out.println(matchScoreModel.getPoint());
        matchScoreCalculationService.addPoint(0);
        System.out.println(matchScoreModel.getPoint());
        matchScoreCalculationService.addPoint(0);
        System.out.println(matchScoreModel.getPoint());

        System.out.println(matchScoreModel.getPoint());
        matchScoreCalculationService.addPoint(1);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);

        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);

        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);

        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);

        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        matchScoreCalculationService.addPoint(0);
        System.out.println("Point");
        System.out.println(matchScoreModel.getPoint());
        System.out.println("Game");
        System.out.println(matchScoreModel.getGame());
        System.out.println("Set");
        System.out.println(matchScoreModel.getSet());
    }
}
